apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  
  resources:
    - ../main_ui/operations/rtsp.yaml
    - ../main_ui_backend_api/operations/backend_db.yaml
    - ../main_ui_backend_api/operations/backend_api.yaml
    - ../footfall_ai_api/operations/footfall.yaml
    - ../genie_api/operations/influxdb.yaml
    - ../genie_api/operations/influxdb-setup.yaml
    - ../genie_api/operations/mssql.yaml
    - ../genie_api/operations/mssql-setup.yaml
    - ../genie_api/operations/genie-api.yaml
    - ../genie_api/operations/genie-simulator.yaml
    - ../main_ui/operations/ui.yaml
