apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../genie_api/operations/influxdb.yaml
  - ../genie_api/operations/mssql.yaml
  - ../main_ui_backend_api/operations/backend_db.yaml
